//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Chat_id { get; set; }
        public Nullable<System.Guid> User_id { get; set; }
        public string Text { get; set; }
        public Nullable<System.Guid> Attach_id { get; set; }
        public Nullable<bool> SelfDestructable { get; set; }
        public Nullable<bool> isRead { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual Attaches Attaches { get; set; }
        public virtual Chats Chats { get; set; }
        public virtual Users Users { get; set; }
    }
}
